Stop dashing if button keeps being pressed
amuoz/Aster pull request #42
Opened 2021-05-12 22:22 UTC by FedeIII

2021-05-12 22:45 UTC, amuoz approved these changes

2021-05-16 19:52 UTC, amuoz requested changes

2021-05-16 19:52 UTC, amuoz commented on Source/PlayerController.cpp
> +			isDash = true;
No me termina de molar que haya lógica acoplada del player dentro del playerController. Un playercontroller no debería de saber si estás en dash, eso debería de controlarlo el propio character.

2021-05-16 20:00 UTC, FedeIII commented on Source/PlayerController.cpp
> +			isDash = true;
```suggestion
			isShiftPressed = true;	
```
?

2021-05-16 20:09 UTC, amuoz commented on Source/PlayerController.cpp
> +			isDash = true;
¿Pero si pones isDash = false; al procesar cualquier input entonces si pulsas cualquier tecla durante el dash se corta?

2021-05-16 20:13 UTC, FedeIII commented on Source/PlayerController.cpp
> +			isDash = true;
No es `isDash`, es `isShiftPressed`. Si pulsas shift en cualquier momento, se envia una instruccion de Dash al Player, si dejas apretado shift solo se envia una instruccion (no mil) porque el player controller esta controlando el input del shift para que solo se ejecute una vez hasta que se suelte el shift.

El player controller no sabe nada de cuando se esta haciendo dash o cuando se corta el dash, solo sabe que tiene que enviar la instruccion de dash cuando se aprieta el shift

2021-05-16 20:15 UTC, FedeIII commented on Source/PlayerController.cpp
> +			isDash = true;
El codigo para cortar el dash o para continuar aunque lleguen otras instrucciones durante el dash SI que esta dentro de Player, desde aqui no lo ves

2021-05-16 20:18 UTC, amuoz commented on Source/PlayerController.cpp
> +			isDash = true;
¿Y por qué no puedes llamar a `Character->Dash(direction);` directamente en el key event igual que haces con `Character->Attack();` ?

2021-05-16 20:23 UTC, FedeIII commented on Source/PlayerController.cpp
> +			isDash = true;
Haber empezado por ahi

2021-05-16 20:24 UTC, amuoz commented on Source/PlayerController.cpp
> +			isDash = true;
Trataba de entender por qué necesitas `isShiftPressed`

2021-05-16 20:25 UTC, amuoz commented on Source/PlayerController.cpp
> +			isDash = true;
Tres tristes tigres, tragaban trigo en un trigal, en tres tristes trastos, tragaban trigo tres tristes tigres.

2021-05-16 21:17 UTC, amuoz approved these changes

2021-05-16 21:18 UTC, merged