Feature/player attack
amuoz/Aster pull request #7
Opened 2021-04-25 16:47 UTC by FedeIII

2021-04-25 22:14 UTC, amuoz commented
* Por convención los nombres de los archivos deben coincidir con el nombre de clase que contienen (Rectangle.h RectangleSystem)
* Crearía un archivo de sólo cabecera que contenga todas las definiciones de structs y enums (AsterTypes.h por ejemplo) y que se incluya en common.h
* No consigo compilar el proyecto en win64 (Rectangle is not a type name)

2021-04-26 12:22 UTC, FedeIII commented
> * Por convención los nombres de los archivos deben coincidir con el nombre de clase que contienen (Rectangle.h RectangleSystem)
> * Crearía un archivo de sólo cabecera que contenga todas las definiciones de structs y enums (AsterTypes.h por ejemplo) y que se incluya en common.h
> * No consigo compilar el proyecto en win64 (Rectangle is not a type name)

Renombrados archivos de Rectangle a RectangleSystem

AsterTypes.h creado. Solo he movido ahi enums y structs que he creado en esta PR y en la anterior por no liar a cambios esta PR. En futuras PRs vamos moviendo el resto de enums y structs ahi.

2021-04-26 12:31 UTC, FedeIII commented
Animaciones funcionando, la parte tricky esta en Animation::Play, he añadido comments y nombres de variables explicativos a ver si lo entendemos

2021-04-26 13:00 UTC, FedeIII commented on Aster/Private/Animation.cpp
> +  const int CELL_HEIGHT = 128;
No se si estas medidas se usan en algun otro lado del proyecto, es el temaño en pixels de cada bloque a nivel de texturas: un Sprite que sea 128x128 ocupara un bloque.

Si se usan en algun otro lado, podemos plantearnos un archivo de constantes globales

2021-04-26 13:04 UTC, thenanox requested changes

2021-04-26 13:04 UTC, thenanox commented on Aster/Private/Animation.cpp
> +  const int CELL_WIDTH = 128;
podriamos sacar esto a configuracion? tendria sentido? por no atarnos a 128

2021-04-26 13:04 UTC, thenanox commented on Aster/Private/Animation.cpp
> +  ReadFileLines(projectSrcDir + "/Aster/Textures/" + filename + ".txt", m_frames);
veo que poner .txt nos obliga quizas tontamente? me refiero .csv o .json podrian ser formatos que quizas nos interesen, y quizas le pasaria el tipo en plan ReadFileLinesAs(mandangafile, txt, frames)

2021-04-26 13:04 UTC, thenanox commented on Aster/Private/Player.cpp
> +Player::Player(glm::vec3 pos, glm::vec3 size, Sprite *sprite, glm::vec3 color, glm::vec3 velocity) : Actor(pos, size, sprite, color, velocity)
necesitamos un linter cuanto antes pa empezar a limitar estas mierdas aunque nos duela

2021-04-26 13:04 UTC, thenanox commented on Aster/Private/Sprite.cpp
> +void Sprite::Draw(AnimationType type, SpriteRenderer &renderer, double deltatime, glm::vec2 position, glm::vec2 size = glm::vec2(10.0f, 10.0f), float rotate = 0.0f, glm::vec3 color = glm::vec3(1.0f))
empiezo a sentir que pintar y animar se estan acoplando un poco de mas, pero esto entiendo que no es algo trivial

2021-04-26 13:04 UTC, thenanox commented on Aster/Public/Game.h
> +	void framebuffer_size_callback(GLFWwindow* window, int width, int height);
esto entiendo que era para cuando se cambiaba la resoucion no? de todos modos en game.cpp no tenemos nada no?

2021-04-26 13:04 UTC, thenanox commented on Aster/Public/Transform.h
> +		return tarnslation * scal * Rotation;
lost in tarnslation

2021-04-26 13:04 UTC, thenanox commented on Aster/Public/Transform.h
> +		glm::mat4 Rotation = glm::rotate(glm::mat4(1.0f), angle, glm::vec3(0.0f, 0.0f, 1.0f));
rotation en minuscula por consistencia?

2021-04-26 13:27 UTC, FedeIII commented on Aster/Private/Animation.cpp
> +  ReadFileLines(projectSrcDir + "/Aster/Textures/" + filename + ".txt", m_frames);
Tu puedes pasar cualquier extension que quieras a ReadFileLines. Por convencion, todos los archivos de animaciones estan en .txt, pero los de niveles estan en .lvl, por ejemplo, y se usa esta misma funcion

2021-04-26 13:28 UTC, FedeIII commented on Aster/Private/Player.cpp
> +Player::Player(glm::vec3 pos, glm::vec3 size, Sprite *sprite, glm::vec3 color, glm::vec3 velocity) : Actor(pos, size, sprite, color, velocity)
yo lo tengo puesto, a veces autoformateo y hace esas cosas :S

2021-04-26 13:30 UTC, FedeIII commented on Aster/Private/Animation.cpp
> +  const int CELL_WIDTH = 128;
He puesto un comment justo una linea abajo, por ahora solo tiene sentido aqui, pero podemos sacarlo a un archivo de constantes mas adelante, no liaria mas esta PR

2021-04-26 13:31 UTC, FedeIII commented on Aster/Private/Sprite.cpp
> +void Sprite::Draw(AnimationType type, SpriteRenderer &renderer, double deltatime, glm::vec2 position, glm::vec2 size = glm::vec2(10.0f, 10.0f), float rotate = 0.0f, glm::vec3 color = glm::vec3(1.0f))
Sprite, Animation y SpriteRenderer tienen mucho lio de codigo y dependencias, cuando entendamos por que funciona esto, miramos como reordenarlo todo

2021-04-26 13:33 UTC, FedeIII commented on Aster/Public/Game.h
> +	void framebuffer_size_callback(GLFWwindow* window, int width, int height);
residuos del refactor de muoz, eliminado

2021-04-26 13:35 UTC, FedeIII commented on Aster/Public/Transform.h
> +		return tarnslation * scal * Rotation;
copy&paste de un ejemplo de intarnet, esta clase no se usa, la borro

2021-04-26 13:35 UTC, FedeIII commented on Aster/Public/Transform.h
> +		glm::mat4 Rotation = glm::rotate(glm::mat4(1.0f), angle, glm::vec3(0.0f, 0.0f, 1.0f));
que no se usa!

2021-04-26 13:35 UTC, thenanox commented on Aster/Private/Animation.cpp
> +  ReadFileLines(projectSrcDir + "/Aster/Textures/" + filename + ".txt", m_frames);
ok aun asi, entiendo que capa un poco que las animaciones tengan que ser en .txt por cuyons, aunque es cierto que luego no tenemos ningun convenio del formato internamente..

2021-04-26 13:44 UTC, FedeIII commented on Aster/Private/Animation.cpp
> +  ReadFileLines(projectSrcDir + "/Aster/Textures/" + filename + ".txt", m_frames);
cambiadas animaciones a .anim

2021-04-26 13:45 UTC, thenanox approved these changes

2021-04-27 19:04 UTC, amuoz approved these changes
Good job

2021-04-27 19:04 UTC, merged